Repository ktgibson/HelloWorldDirectory, pull requests merged in 2020-10, with the labels that each got.

#1 add python
  helloWorld.py
Labels: Hacktober

#2 Adding js example
  helloworld.js
Labels: Hacktoberfest

#3 Add r
  helloworld.r
Labels: Hacktoberfest

#4 Add ruby helloworld
  helloworld.rb
Labels: Hacktoberfest

#5 Add folder and move code
  helloWorld/helloWorld.js
  helloWorld/helloWorld.py
  helloWorld/helloWorld.r
  helloWorld/helloWorld.rb
Labels: Hacktoberfest

#7 Hello World in C
  helloWorld/helloWorld.c
Labels: Hacktoberfest

#8 Well, that was a strange one...
  helloWorld/haiworld.lol
Labels: Hacktoberfest

#9 Create helloWorld-d-folt.cpp
  helloWorld/helloWorld-d-folt.cpp
Labels: Hacktoberfest

#11 Ill be back, baby
  helloWorld/helloWorld.arnoldc
Labels: Hacktoberfest

#10 Hello World in lua
  helloWorld/helloWorld.lua
Labels: Hacktoberfest

#15 Rust HelloWorld Program
  helloWorld/HelloWorld.rs
Labels: Hacktoberfest2020, hacktoberfest-accepted

#16 HelloWorld.php
  helloWorld/HelloWorld.php
Labels: Hacktoberfest2020, hacktoberfest-accepted

#17 HelloWorld.sc
  helloWorld/HelloWorld.sc
Labels: Hacktoberfest2020, hacktoberfest-accepted

#19 Create helloWorld.fs
  helloWorld/helloWorld.fs
Labels: Hacktoberfest2020, hacktoberfest-accepted

#20 Hello World in bash shell.
  helloWorld/helloWorld.sh
Labels: Hacktoberfest2020, hacktoberfest-accepted
